### ISSUE TITLE
make: *** [build/util.o] Error 1

### ISSUE THREAD

**Issue by Alavi1412** [Nexusoft/PrimePoolMiner#14]
When I try to make the code with `make MARCHFLAGS=-march=native -f makefile` I got the following error:
 ```
...
                from util.cpp:1:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
util.cpp:40:19: error: invalid use of incomplete type ‘const BIGNUM {aka const struct bignum_st}’
   g->_mp_size = bn->top;
                   ^~
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:14,
                 from util.h:6,
                 from util.cpp:1:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
util.cpp:41:8: error: invalid use of incomplete type ‘const BIGNUM {aka const struct bignum_st}’
   if(bn->neg)
        ^~
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:14,
                 from util.h:6,
                 from util.cpp:1:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
makefile:124: recipe for target 'build/util.o' failed
make: *** [build/util.o] Error 1

```

**Comment by Alavi1412** [comment]
No answer?

**Comment by huglester** [comment]
did you solve?

**Comment by dbigge** [comment]
makefile has pgi paths for Linux 16 and 17....just a guess...are you using Linux 18?

**Comment by dbigge** [comment]
If you are running Ubuntu 18 then pgi missing and build path for util.o isn't valid.

**Comment by jamesbrink** [comment]
@Alavi1412 these errors might be related to the version of OpenSSL you are compiling against. If i remember correctly distros such as ubuntu now have two packages for OpenSSL as there were items that were deprecated. 

On Ubuntu I believe the package is openssl1.0 and openssl1.0-dev. It will likely solve your compilation issue. 

I have a docker variant of this using alpine linux, might be helpful for reference or to use (I do not actively update it)
https://github.com/jamesbrink/docker-prime-pool-miner/

**Comment by l4r1k4** [comment]
I confirm installing openssl1.0-dev and libssl1.0-dev allows to compile in Ubuntu 18.04.3 LTS
